--1. Tạo các quan hệ 

CREATE DATABASE QLX

USE QLX

CREATE TABLE NHANVIEN
(
	MANV CHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(20),
	NGAYVL SMALLDATETIME,
	HSLUONG numeric(4,2),
	MAPHONG CHAR(5)
)

CREATE TABLE PHONGBAN
(
	MAPHONG CHAR(5) PRIMARY KEY,
	TENPHONG VARCHAR(25),
	TRUONGPHONG CHAR(5) FOREIGN KEY REFERENCES NHANVIEN(MANV),
)

CREATE TABLE XE
	MAXE CHAR(5) PRIMARY KEY,
	LOAIXE VARCHAR(20),
	SOCHONGOI INT,
	NAMSX INT
)

CREATE TABLE PHANCONG
(
	MAPC CHAR(5) PRIMARY KEY,
	MANV CHAR(5) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	MAXE CHAR(5) FOREIGN KEY REFERENCES XE(MAXE),
	NGAYDI SMALLDATETIME,
	NGAYVE SMALLDATETIME,
	NOIDEN VARCHAR(25)
)

ALTER TABLE NHANVIEN
ADD CONSTRAINT fk_NV_PB FOREIGN KEY (MAPHONG) REFERENCES PHONGBAN(MAPHONG)


-- 2.1. Năm sản xuất của xe loại Toyota phải từ năm 2006 trở về sau.
CREATE TRIGGER TRG_XE ON XE AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT *
        FROM INSERTED I
        WHERE I.LOAIXE = 'Toyota' AND I.NAMSX < 2006 
    )
    BEGIN
        RAISERROR('Lỗi: Năm sản xuất của xe loại Toyota phải từ năm 2006 trở về sau.', 16, 1);
        ROLLBACK TRANSACTION;
    END
	ELSE
	BEGIN
		PRINT('Thêm mới một xe thành công')
	END
END

-- 2.2. Nhân viên thuộc phòng lái xe “Ngoại thành” chỉ được phân công lái xe loại Toyota. 
CREATE TRIGGER TRG_NV_PC ON NHANVIEN AFTER INSERT, UPDATE 
AS
BEGIN
    IF EXISTS (
        SELECT *
        FROM INSERTED I, XE X, PHANCONG PC
        WHERE I.MANV = PC.MANV AND X.MAXE = PC.MAXE AND I.MAPHONG = 'Ngoại thành' AND X.LOAIXE NOT IN ('Toyota') 
    )
    BEGIN
        RAISERROR('Lỗi: Nhân viên thuộc phòng lái xe “Ngoại thành” chỉ được phân công lái xe loại Toyota.', 16, 1);
        ROLLBACK TRANSACTION;
    END
	ELSE
	BEGIN
		PRINT('Thêm mới nhân viên thành công')
	END
END


-- 3.1. Tìm nhân viên (MaNV,HoTen) thuộc phòng lái xe “Nội thành” được phân công lái loại xe Toyota có số chỗ ngồi là 4.
SELECT NV.MANV, NV.HOTEN
FROM NHANVIEN NV, XE X, PHANCONG PC
WHERE NV.MANV = PC.MANV AND
	  X.MAXE = PC.MAXE AND
	  NV.MAPHONG = 'Nội thành' AND X.LOAIXE = 'Toyota' AND X.SOCHONGOI = 4

-- 3.2. Tìm nhân viên(MANV,HoTen) là trưởng phòng được phân công lái tất cả các loại xe.
SELECT NV.MANV, NV.HOTEN
FROM NHANVIEN NV, XE X, PHANCONG PC, PHONGBAN PB
WHERE NV.MANV = PB.TRUONGPHONG AND NV.MANV = PC.MANV AND PC.MAXE = X.MAXE
GROUP BY NV.MANV, NV.HOTEN
HAVING COUNT(DISTINCT X.LOAIXE) = (SELECT COUNT(DISTINCT XE.LOAIXE) FROM XE) 

-- 3.3. Trong mỗi phòng ban, tìm nhân viên (MaNV,HoTen) được phân công lái ít nhất loại xe Toyota. 
SELECT A.MAPHONG, A.MANV, A.HOTEN, A.MIN(SL) FROM (
	SELECT PB.MAPHONG, NV.MANV, NV.HOTEN, COUNT(DISTINCT MAXE) AS SL
	FROM NHANVIEN NV, XE X, PHANCONG PC, PHONGBAN PB
	WHERE NV.MANV = PB.TRUONGPHONG AND NV.MANV = PC.MANV AND PC.MAXE = X.MAXE AND X.LOAIXE = 'Toyota'
	GROUP BY PB.MAPHONG, NV.MANV, NV.HOTEN) A

