-- 1. Tạo các quan hệ 

CREATE DATABASE QLDG

USE QLDG

CREATE TABLE DOCGIA
(
	MADG CHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(30),
	NGAYSINH SMALLDATETIME,
	DIACHI VARCHAR(30),
	SODT VARCHAR(15)
)

CREATE TABLE SACH
(
	MASACH CHAR(5) PRIMARY KEY,
	TENSACH VARCHAR(25),
	THELOAI VARCHAR(25),
	NHAXUATBAN VARCHAR(30)
)

CREATE TABLE PHIEUTHUE
	MAPT CHAR(5) PRIMARY KEY,
	MADG CHAR(5) FOREIGN KEY REFERENCES DOCGIA(MADG),
	NGAYTHUE SMALLDATETIME,
	NGAYTRA SMALLDATETIME,
	SOSACHTHUE INT
)

CREATE TABLE CHITIET_PT
(
	MAPT CHAR(5) FOREIGN KEY REFERENCES PHIEUTHUE(MAPT),
	MASACH CHAR(5) FOREIGN KEY REFERENCES SACH(MASACH),
	PRIMARY KEY(MAPT, MASACH)
)

-- 2.1. Mỗi lần thuê sách, độc giả không được thuê quá 10 ngày
CREATE TRIGGER TRG_PT ON PHIEUTHUE AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT *
        FROM INSERTED I
        WHERE I.NGAYTRA - I.NGAYTHUE > '00/00/10' 
    )
    BEGIN
        RAISERROR('Lỗi: Mỗi lần thuê sách, độc giả không được thuê quá 10 ngày.', 16, 1);
        ROLLBACK TRANSACTION;
    END
	ELSE
	BEGIN
		PRINT('Thêm mới một phiếu xe thành công')
	END
END

-- 2.2. Số sách thuê trong bảng phiếu thuê bằng tổng số lần thuê sách có trong bảng chi tiết phiếu thuê. 
CREATE TRIGGER TRG_CTPT ON CHITIET_PT FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @COUNT_SOLANTHUESACH INT, @MAPT CHAR(5)
	SELECT @COUNT_SOLANTHUESACH = COUNT(*), @MAPT = MAPT FROM INSERTED
	GROUP BY MAPT

	UPDATE PHIEUTHUE PT
	SET PT.SOSACHTHUE += @COUNT_SOLANTHUESACH
	WHERE PT.MAPT = @MAPT
END

CREATE TRIGGER TRG_DEL_CTPT ON CHITIET_PT FOR DELETE
AS
BEGIN
	DECLARE @COUNT_SOLANTHUESACH INT, @MAPT CHAR(5)
	SELECT @COUNT_SOLANTHUESACH = COUNT(*), @MAPT = MAPT FROM INSERTED
	GROUP BY MAPT

	UPDATE PHIEUTHUE PT
	SET PT.SOSACHTHUE -= @COUNT_SOLANTHUESACH
	WHERE PT.MAPT = @MAPT
END

-- 3.1. Tìm các độc giả (MaDG,HoTen) đã thuê sách thuộc thể loại “Tin học” trong năm 2007.
SELECT DG.MADG, DG.HOTEN
FROM DOCGIA DG, SACH S, PHIEUTHUE PT, CHITIET_PT CT
WHERE DG.MADG = PT.MADG AND
	  PT.MAPT = CT.MAPT AND
	  S.MASACH = CT.MASACH AND
	  S.THELOAI = 'Tin học' AND YEAR(PT.NGAYTHUE) = 2007

-- 3.2. Tìm các độc giả (MaDG,HoTen) đã thuê nhiều thể loại sách nhất
SELECT A.MADG, A.HOTEN FROM (
	SELECT DG.MADG, DG.HOTEN, RANK() OVER (ORDER BY COUNT(DISTINCT S.THELOAI) DESC) RANK_SLTLSACH
	FROM DOCGIA DG, SACH S, PHIEUTHUE PT, CHITIET_PT CT
	WHERE DG.MADG = PT.MADG AND PT.MAPT = CT.MAPT AND S.MASACH = CT.MASACH
	GROUP BY DG.MADG, DG.HOTEN) A
WHERE RANK_SLTLSACH = 1

-- 3.3. Trong mỗi thể loại sách, cho biết tên sách được thuê nhiều nhất.
SELECT A.THELOAI, A.MASACH, A.TENSACH, A.MAX(SLTHUE) FROM (
	SELECT S.THELOAI, S.MASACH, S.TENSACH, COUNT(DISTINCT MASACH) AS SLTHUE
	FROM SACH S, CHITIET_PT CT
	WHERE S.MASACH = CT.MASACH
	GROUP BY S.THELOAI, S.MASACH, S.TENSACH) A

